### ISSUE TITLE
None of my timestamps show up in the entities dropdown

### ISSUE THREAD

**Issue by OmgImAlexis** [kirbo/ha-lovelace-elapsed-time-card#2]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** Latest

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**
The only entity that shows in the dropdowns is my phone's distance which shouldn't even be showing. Yet the uptime for my network devices are all missing even though they're timestamps.

<img width="499" alt="Screen Shot 2021-05-24 at 8 48 02 pm" src="https://user-images.githubusercontent.com/6525926/119340264-76aa6f80-bcd1-11eb-8f06-9cff0752d591.png">

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by Kirbo** [comment]
Sorry for taking a while to answer;

I'm not 100% sure if I remember correctly, but if I'm not incorrect, it lists only the sensors that have `unit_of_measurement` set to be either `h`, `m` or `s` (hours, minutes or seconds).

Now that it shows only `sensor.eve_distance`, I think it might have `unit_of_measurement = m`, meaning meters instead of minutes. I'm not sure where did I came up with `h`, `m` and `s`, are they correct ones or should they rather be `hours`, `minutes`, `seconds` or something else? 😬

Either way, for now you should get the sensors you want to see there, by defining the `unit_of_measurement` for one of the ones stated earlier.

Also added this into [README.md](https://github.com/kirbo/ha-lovelace-elapsed-time-card#notice)

Please let me know if this didn't solve your issue and if it did, could you kindly close this issue? 🙂

**Comment by OmgImAlexis** [comment]
> I'm not sure where did I came up with h, m and s, are they correct ones or should they rather be hours, minutes, seconds or something else? 

I don't think it should be filtering by that at all since timestamps are going to be a ISO string not a number.

**Comment by Kirbo** [comment]
Actually now that I checked the code a bit better, I noticed that it doesn't filter the entities only based on the `unit_of_measurement`, it also includes entities that contain either `has_time` or `has_date` attribute.

So, if you're using e.g. `history_stat` platform, it will automatically set the correct `unit_of_measurement`, therefore these sensors are listed in this addon. Also all the `input_datetime` sensors that contain either `has_time` or `has_date` attribute, are listed.

I updated the README.md again with few examples:
- https://github.com/kirbo/ha-lovelace-elapsed-time-card#notice
- https://github.com/kirbo/ha-lovelace-elapsed-time-card#example-sensors

Not sure is this still not good enough or if I'm filtering the list somehow wrong, but I personally don't want the addon to list _EVERY_ entity, since MY Home Assistant contains currently 1040 entities and only 52 entities that contain time (that are listed in this addon).

https://www.home-assistant.io/integrations/history_stats
https://www.home-assistant.io/integrations/input_datetime

**Comment by Kirbo** [comment]
Could you provide me an example of the entities you want to list there? Are they something like e.g. Unifi device uptime sensors?
And perhaps also a description on what are you going to do with this addon, as I'm currently not completely sure whether you can achieve the expected outcome with my addon..

As of now that I added in the filtered list entities containing attribute `device_class: timestamp`, like my Unifi uptime sensors currently are, I'm quite certain you cannot do anything reasonable with these sensors..

Here's one of my devices Unifi uptime sensor:
![image](https://user-images.githubusercontent.com/1077974/120066074-70274980-c07d-11eb-96c5-047d77226c58.png)

Example configuration:
```yaml
format: Time Elapsed
time_format: 1h 5m
type: 'custom:elapsed-time-card'
name: Washing Mashine Uptime
icon: washing-machine
time_today: sensor.bosch_washing_machine_uptime
```
Looks like this:
![image](https://user-images.githubusercontent.com/1077974/120066206-3c98ef00-c07e-11eb-9c48-3dddfa937e82.png)

I'm not sure at all what is the state supposed to be, since it's basically a timestamp of current day and it doesn't contain any other useful information, what am I supposed to do with it.. 😬  Like, if you compare the data above into Shelly Plugs uptime sensor, it contains more useful information (and it also automatically has the `unit_of_measurement: h`):
![120066178-00658e80-c07e-11eb-8bb5-72c819e6a3bd](https://user-images.githubusercontent.com/1077974/120066423-f42e0100-c07e-11eb-9c17-3555c26c6247.png)


With this sensor I could use this configuration:
```yaml
format: Time Elapsed
time_format: 1h 5m
type: 'custom:elapsed-time-card'
name: TV-Stand Uptime
icon: television
time_today: sensor.shelly_tv_taso_uptime
```

And it would look like this:
![image](https://user-images.githubusercontent.com/1077974/120066200-2f7c0000-c07e-11eb-9cc7-b5789d927179.png)

**Comment by Kirbo** [comment]
Well, I just added a support for `device_class: timestamp` entities as well. Let me know if this resolves your issue or not.
https://github.com/kirbo/ha-lovelace-elapsed-time-card/releases/tag/0.4.0

**Comment by OmgImAlexis** [comment]
Sorry for not getting back to you quicker. The newest update that enables `timestamp` entities works well only the value is incorrect.

The value is currently `2021-05-31T12:22:00.837207+09:30`.
I would have expected to the equivalent to `1h` not `-18778d 2h 52m`.

<img width="509" alt="Screen Shot 2021-05-31 at 1 24 32 pm" src="https://user-images.githubusercontent.com/6525926/120137486-9121a300-c213-11eb-8cdf-777cb2833e39.png">

```yaml
type: grid
cards:
  - type: entities
    entities:
      - entity: sensor.alexis_apple_watch_series_5_uptime
  - type: 'custom:elapsed-time-card'
    format: Time Left
    time_format: 1h 5m
    time_today: sensor.alexis_apple_watch_series_5_uptime
  - type: 'custom:logbook-card'
    entity: sensor.alexis_apple_watch_series_5_uptime
columns: 1
square: false
```
